name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Python3.8 PyInstaller Linux AMD64
      # You may pin to the exact commit or the version.
      # uses: action-python/pyinstaller-py3.8@1839eaaab51a950d6a80bf199c2527cfb045421b
      uses: action-python/pyinstaller-py3.8@v1.0.0
      with:
        # Directory containing source code & .spec file (optional requirements.txt).
        path: # default is src
        # Specify a custom URL for PYPI
        pypi_url: # optional, default is https://pypi.python.org/
        # Specify a custom URL for PYPI Index
        pypi_index_url: # optional, default is https://pypi.python.org/simple
        # Specify a file path for .spec file
        spec: # optional, default is 
        # Specify a file path for requirements.txt file
        requirements: # optional, default is requirements.txt
        # Rename the binary file, this will only work when you have --onefile binary.
        rename: # optional, default is 


name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: r3d11/dev-sec-ops-api
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
